services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
        - APP_PORT=${APP_PORT}
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "${APP_PORT_FORWARD}:${APP_PORT}"
    volumes:
      - ./:/opt/apps/app
      - mvn_deps:/opt/apps/maven/repository
    env_file:
      - .env
    networks:
      - app
      - accessible
    labels:
      - traefik.enable=true
      - traefik.http.routers.games.rule=Host(`games.henrotaym.ip-ddns.com`)
      - traefik.http.routers.games.tls=true
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "${DB_PORT_FORWARD}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD_ROOT}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE_TEST: "${DB_DATABASE_TEST}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./devops/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    restart: unless-stopped
  kafka:
    image: confluentinc/cp-kafka:7.9.1
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/var/lib/kafka/data
      - ./devops/kafka/server.properties.custom:/etc/kafka/server.properties.custom
      - ./devops/kafka/start.sh:/opt/kafka/start.sh
    command: ["/bin/bash", "/opt/kafka/start.sh"]
    networks:
      - app

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 48081:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: default
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
    depends_on:
      - kafka
    networks:
      - app

networks:
  app:
    driver: bridge
  accessible:
    external: true
volumes:
  mysql_data:
    driver: local
  mvn_deps:
    driver: local
  kafka_data:
    driver: local
  
